### ISSUE TITLE
How do I change the text color of the phone number prefix? + bug when choosing USA number

### ISSUE THREAD

**Issue by nmalchy** [CdTgr/vue3-q-tel-input#37]
Hey thanks for making this awesome component!

However I'm not sure how to customize the text color of the number prefix, for example my component usage is this:

```
<vue3-q-tel-input
    v-model:tel="phoneNumber"
    color="white"
    label-color="white"
    input-class="text-amber-13"
    outlined
 />
```

But it looks like this:
![image](https://github.com/CdTgr/vue3-q-tel-input/assets/50896885/9f6d357c-5089-4477-b923-47fce94efe5a)

Also, there is a bug, when I click on the USA phone number and start typing, it automatically defaults to the flag in the screenshot above.

**Comment by CdTgr** [comment]
@nmalchy which color are you trying to change? I can see am amber color which you've applied to the text and its applied as well.

Regarding the automatic switching, you can disable this by setting the property `disableAutoCountrySelection` which was addressed in the issue #34.

The automatic switching happens because there are similar code for countries (eg: Canada and USA have +1 ).
